### ISSUE TITLE
Request: Can you make this available outside Chine mainland?

### ISSUE THREAD

**Issue by plat1231** [georgezhao2010/fordpass_china#8]
Hi all, this looks amazing! As I'm in Europe, I can't use it though… And that's a shame ;)
Is there any change you can make this integration usable outside China mainland?

Thanks and keep up the great work!

**Comment by georgezhao2010** [comment]
You should try this https://github.com/itchannel/fordpass-ha

**Comment by plat1231** [comment]
> You should try this https://github.com/itchannel/fordpass-ha

Thank you for sharing. I already use this integration, but yours is better looking (and has (visual) window/lock status) ;)

**Comment by georgezhao2010** [comment]
> > You should try this https://github.com/itchannel/fordpass-ha
> 
> Thank you for sharing. I already use this integration, but yours is better looking (and has (visual) window/lock status) ;)

Do you mean the card is cool?

This intergration provides similar functionality you are using, like window status and lock/unlock etc, it looks better because those cards?

Do you need the configurations of my cards?

**Comment by plat1231** [comment]
> > > You should try this https://github.com/itchannel/fordpass-ha
> > 
> > 
> > Thank you for sharing. I already use this integration, but yours is better looking (and has (visual) window/lock status) ;)
> 
> Do you mean the card is cool?
> 
> This intergration provides similar functionality you are using, like window status and lock/unlock etc, it looks better because those cards?
> 
> Do you need the configurations of my cards?

Indeed, the card looks very cool. Sharing that configuration might help me, thanks

**Comment by georgezhao2010** [comment]
> > > > You should try this https://github.com/itchannel/fordpass-ha
> > > 
> > > 
> > > Thank you for sharing. I already use this integration, but yours is better looking (and has (visual) window/lock status) ;)
> > 
> > 
> > Do you mean the card is cool?
> > This intergration provides similar functionality you are using, like window status and lock/unlock etc, it looks better because those cards?
> > Do you need the configurations of my cards?
> 
> Indeed, the card looks very cool. Sharing that configuration might help me, thanks

Configuration of cards
```
type: vertical-stack
cards:
  - type: vertical-stack
    cards:
      - type: picture-elements
        image: /local/images/focus.png
        entity: binary_sensor.XXXXXXXXXXXXXXXXX_ignition_status
        elements:
          - type: state-icon
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_driver_door
            style:
              top: 80%
              left: 27%
          - type: state-label
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_driver_door
            style:
              top: 80%
              left: 34%
          - type: state-icon
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_driver_window
            style:
              top: 87%
              left: 27%
          - type: state-label
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_driver_window
            style:
              top: 87%
              left: 34%
              text-align: left
          - type: state-icon
            entity: sensor.XXXXXXXXXXXXXXXXX_left_front_tire_pressure
            style:
              top: 94%
              left: 27%
          - type: state-label
            entity: sensor.XXXXXXXXXXXXXXXXX_left_front_tire_pressure
            style:
              top: 94%
              left: 37%
              text-align: left
          - type: state-icon
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_left_rear_door
            style:
              top: 80%
              left: 67%
          - type: state-label
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_left_rear_door
            style:
              top: 80%
              left: 74%
          - type: state-icon
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_rear_driver_window
            style:
              top: 87%
              left: 67%
          - type: state-label
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_rear_driver_window
            style:
              top: 87%
              left: 74%
              text-align: left
          - type: state-icon
            entity: sensor.XXXXXXXXXXXXXXXXX_left_rear_tire_pressure
            style:
              top: 94%
              left: 67%
          - type: state-label
            entity: sensor.XXXXXXXXXXXXXXXXX_left_rear_tire_pressure
            style:
              top: 94%
              left: 77%
              text-align: left
          - type: state-icon
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_passenger_door
            style:
              top: 5%
              left: 27%
          - type: state-label
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_passenger_door
            style:
              top: 5%
              left: 34%
          - type: state-icon
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_passenger_window
            style:
              top: 12%
              left: 27%
          - type: state-label
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_passenger_window
            style:
              top: 12%
              left: 34%
              text-align: left
          - type: state-icon
            entity: sensor.XXXXXXXXXXXXXXXXX_right_front_tire_pressure
            style:
              top: 19%
              left: 27%
          - type: state-label
            entity: sensor.XXXXXXXXXXXXXXXXX_right_front_tire_pressure
            style:
              top: 19%
              left: 37%
              text-align: left
          - type: state-icon
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_right_rear_door
            style:
              top: 5%
              left: 67%
          - type: state-label
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_right_rear_door
            style:
              top: 5%
              left: 74%
          - type: state-icon
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_rear_pass_window
            style:
              top: 12%
              left: 67%
          - type: state-label
            entity: binary_sensor.XXXXXXXXXXXXXXXXX_rear_pass_window
            style:
              top: 12%
              left: 74%
              text-align: left
          - type: state-icon
            entity: sensor.XXXXXXXXXXXXXXXXX_right_rear_tire_pressure
            style:
              top: 19%
              left: 67%
          - type: state-label
            entity: sensor.XXXXXXXXXXXXXXXXX_right_rear_tire_pressure
            style:
              top: 19%
              left: 77%
              text-align: left
  - type: entities
    entities:
      - entity: sensor.XXXXXXXXXXXXXXXXX_odometer
        name: Odometer
  - type: horizontal-stack
    cards:
      - type: gauge
        entity: sensor.XXXXXXXXXXXXXXXXX_fuel
        min: 0
        max: 100
        severity:
          green: 50
          yellow: 30
          red: 10
        name: Fuel
      - type: gauge
        entity: sensor.XXXXXXXXXXXXXXXXX_range
        min: 0
        max: 700
        severity:
          green: 200
          yellow: 100
          red: 50
        name: Range
      - type: gauge
        entity: sensor.XXXXXXXXXXXXXXXXX_oil_life
        min: 0
        max: 100
        severity:
          green: 50
          yellow: 30
          red: 10
        name: Oil Life
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - type: custom:toggle-control-button
            entity: lock.XXXXXXXXXXXXXXXXX_lock
            name: Lock
            customTheme: true
            unlockedColor: RED
            lockedColor: '#43A047'
            customUnlockingText: WAIT
            customLockingText: WAIT
            width: 70px
            state_color: true
      - type: entities
        entities:
          - type: custom:toggle-control-button
            name: Remote Start
            entity: switch.XXXXXXXXXXXXXXXXX_remote_start
            customTheme: true
            isOnColor: RED
            isOffColor: '#43A047'
            isOnTextColor: white
            isOffTextColor: white
            customOnText: STOP
            customOffText: START
            width: 70px
            state_color: true
  - type: glance
    entities:
      - entity: sensor.XXXXXXXXXXXXXXXXX_battery_health
        name: Battery Health
      - entity: sensor.XXXXXXXXXXXXXXXXX_battery_voltage
        name: Battery Voltage
```

You can find `toggle-control-button` in [there](https://github.com/georgezhao2010/lovelace-toggle-control-button)
